"""PrintLink crypto: pairing-token-keyed authenticated encryption for job payloads.

Threat model: anyone on the LAN could sniff or spoof HTTP traffic to port 9100.
The pairing token (issued at share-accept time) doubles as the symmetric key:
both sides already have it, so no key exchange is needed.

Wire format inside the HTTP body (replacing the raw file upload):
  [12B random nonce][AES-GCM ciphertext+tag]

Requires: pip install cryptography
"""
import os
import hashlib
from cryptography.hazmat.primitives.ciphers.aead import AESGCM

NONCE_LEN = 12
TAG_LEN = 16  # implicit in AESGCM output


def _key_from_token(token: str) -> bytes:
    """Derive a stable 256-bit key from the pairing token (normally hex)."""
    try:
        raw = bytes.fromhex(token)
    except ValueError:
        raw = token.encode("utf-8")
    return hashlib.sha256(raw).digest()


def encrypt_payload(plaintext: bytes, token: str) -> bytes:
    """Encrypt a job file for transport. AAD binds it to the token itself."""
    nonce = os.urandom(NONCE_LEN)
    ct = AESGCM(_key_from_token(token)).encrypt(nonce, plaintext, None)
    return nonce + ct


def decrypt_payload(blob: bytes, token: str) -> bytes:
    """Decrypt; raises cryptography.exceptions.InvalidTag on wrong token/tamper."""
    if len(blob) < NONCE_LEN + TAG_LEN:
        raise ValueError("payload too short")
    nonce, ct = blob[:NONCE_LEN], blob[NONCE_LEN:]
    return AESGCM(_key_from_token(token)).decrypt(nonce, ct, None)


def new_pairing_token() -> str:
    """64-char hex token; generated by the host when accepting a share request."""
    return os.urandom(32).hex()
